services:
    api_response_listener:
      class: LesPolypodes\RestOAuthBundle\EventListener\Kernel\ApiResponseListener
      tags:
        - { name: kernel.event_listener, event: kernel.view , priority: 1000 }
      arguments: ["@twig", "@jms_serializer"]