parameters:
#    les_polypodes_rest_o_auth.example.class: LesPolypodes\RestOAuthBundle\Example

services:
#    les_polypodes_rest_o_auth.example:
#        class: %les_polypodes_rest_o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
