parameters:
#    les_polypodessf2_rest_o_auth.example.class: LesPolypodes\sf2RestOAuthBundle\Example

services:
#    les_polypodessf2_rest_o_auth.example:
#        class: %les_polypodessf2_rest_o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
